### ISSUE TITLE
Emacs logo not showing on banner

### ISSUE THREAD

**Issue by NoahDragon** [rakanalh/emacs-dashboard#55]
I got an issue that the logo couldn't display on the banner. Not matter what value I set for the dashboard-startup-banner, the logo doesn't change.

![image](https://user-images.githubusercontent.com/5704064/31679449-1caa03d2-b33f-11e7-8b6c-e3b1bc1c1256.png)

Any help would be really appreciate.

**Comment by rakanalh** [comment]
Which emacs version are you using?
Dashboard is falling back to ascii banner because your emacs is not compiled with jpeg and png support. 
Try executing: `M-: (image-type-available-p (intern (file-name-extension "test.png")))`
If you see `nil` in the minibuffer, this means  that your emacs doesn't have png support for displaying the logo.

**Comment by NoahDragon** [comment]
@rakanalh Thank you. I ran the statement, it returns nil. I will try to figure out how emacs supports the image.

However, the original welcome image display correctly. BTW, my emacs version is 24.5.1.

**Comment by NoahDragon** [comment]
@rakanalh you are right. Under window, the emacs is not compiled with png support. After following the answers on the https://stackoverflow.com/questions/2650041/emacs-under-windows-and-png-files , my issue resolved.

Thank you.

**Comment by rakanalh** [comment]
Glad i could help :)
